name: C++ Compatibility
inputs:
  gh-token:
    required: true
  client-branch-name:
    required: true
  hazelcast-version:
    required: true
  hazelcast-enterprise-key:
    required: false
runs:
  using: "composite"
  steps:
    - name: Detect Client Version
      shell: bash
      id: compute_client_version
      run: |
        client="${{ inputs.client-branch-name }}"
        echo "CLIENT_VERSION=${client#v}" >> ${GITHUB_OUTPUT}

    # https://github.com/madhead/semver-utils/releases/tag/v4.3.0
    - uses: madhead/semver-utils@36d1e0ed361bd7b4b77665de8093092eaeabe6ba
      id: client-version
      with:
        version: ${{ steps.compute_client_version.outputs.CLIENT_VERSION }}
        compare-to: 5.2.0

    - name: Determine if test with OpenSSL
      shell: bash
      id: with-openssl
      run: |
        if [[ "${{ steps.client-version.outputs.comparison-result }}" = "<" ]]; then
          # Workaround lack of https://github.com/hazelcast/hazelcast-cpp-client/pull/1098
          echo "WITH_OPENSSL=OFF" >> ${GITHUB_OUTPUT}
        else
          echo "WITH_OPENSSL=ON" >> ${GITHUB_OUTPUT}
        fi

    - uses: ./.github/actions/build-test/ubuntu-x86_64
      with:
        GH_TOKEN: ${{ inputs.gh-token }}
        BOOST_VERSION: 1.76.0
        THRIFT_VERSION: 0.13.0
        # Running against already-released tags, compiler warnings and additional validation are unhelpful when code is static
        BUILD_TYPE: Release
        SHARED_LIBS_TOGGLE: ON
        OPENSSL_TOGGLE: ${{ steps.with-openssl.outputs.WITH_OPENSSL }}
        RUN_TESTS: true
        HAZELCAST_ENTERPRISE_KEY: ${{ inputs.hazelcast-enterprise-key }}
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        HZ_TEST_AWS_INSTANCE_PRIVATE_IP:
      env:
        GTEST_FILTER: -*Aws*:*DescribeInstancesTest*
