/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "remote_controller_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace hazelcast { namespace client { namespace test { namespace remote {

int _kLangValues[] = {
  Lang::JAVASCRIPT,
  Lang::GROOVY,
  Lang::PYTHON,
  Lang::RUBY
};
const char* _kLangNames[] = {
  "JAVASCRIPT",
  "GROOVY",
  "PYTHON",
  "RUBY"
};
const std::map<int, const char*> _Lang_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kLangValues, _kLangNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const Lang::type& val) {
  std::map<int, const char*>::const_iterator it = _Lang_VALUES_TO_NAMES.find(val);
  if (it != _Lang_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const Lang::type& val) {
  std::map<int, const char*>::const_iterator it = _Lang_VALUES_TO_NAMES.find(val);
  if (it != _Lang_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


Cluster::~Cluster() noexcept {
}


void Cluster::__set_id(const std::string& val) {
  this->id = val;
}
std::ostream& operator<<(std::ostream& out, const Cluster& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Cluster::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Cluster::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Cluster");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Cluster &a, Cluster &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.__isset, b.__isset);
}

Cluster::Cluster(const Cluster& other0) {
  id = other0.id;
  __isset = other0.__isset;
}
Cluster& Cluster::operator=(const Cluster& other1) {
  id = other1.id;
  __isset = other1.__isset;
  return *this;
}
void Cluster::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Cluster(";
  out << "id=" << to_string(id);
  out << ")";
}


CloudCluster::~CloudCluster() noexcept {
}


void CloudCluster::__set_id(const std::string& val) {
  this->id = val;
}

void CloudCluster::__set_name(const std::string& val) {
  this->name = val;
}

void CloudCluster::__set_nameForConnect(const std::string& val) {
  this->nameForConnect = val;
}

void CloudCluster::__set_hazelcastVersion(const std::string& val) {
  this->hazelcastVersion = val;
}

void CloudCluster::__set_isTlsEnabled(const bool val) {
  this->isTlsEnabled = val;
}

void CloudCluster::__set_state(const std::string& val) {
  this->state = val;
}

void CloudCluster::__set_token(const std::string& val) {
  this->token = val;
}

void CloudCluster::__set_certificatePath(const std::string& val) {
  this->certificatePath = val;
}

void CloudCluster::__set_tlsPassword(const std::string& val) {
  this->tlsPassword = val;
}
std::ostream& operator<<(std::ostream& out, const CloudCluster& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CloudCluster::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->nameForConnect);
          this->__isset.nameForConnect = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->hazelcastVersion);
          this->__isset.hazelcastVersion = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isTlsEnabled);
          this->__isset.isTlsEnabled = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->state);
          this->__isset.state = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->token);
          this->__isset.token = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->certificatePath);
          this->__isset.certificatePath = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->tlsPassword);
          this->__isset.tlsPassword = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CloudCluster::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CloudCluster");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("nameForConnect", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->nameForConnect);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("hazelcastVersion", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->hazelcastVersion);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("isTlsEnabled", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->isTlsEnabled);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("state", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->state);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("token", ::apache::thrift::protocol::T_STRING, 7);
  xfer += oprot->writeString(this->token);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("certificatePath", ::apache::thrift::protocol::T_STRING, 8);
  xfer += oprot->writeString(this->certificatePath);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("tlsPassword", ::apache::thrift::protocol::T_STRING, 9);
  xfer += oprot->writeString(this->tlsPassword);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CloudCluster &a, CloudCluster &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.name, b.name);
  swap(a.nameForConnect, b.nameForConnect);
  swap(a.hazelcastVersion, b.hazelcastVersion);
  swap(a.isTlsEnabled, b.isTlsEnabled);
  swap(a.state, b.state);
  swap(a.token, b.token);
  swap(a.certificatePath, b.certificatePath);
  swap(a.tlsPassword, b.tlsPassword);
  swap(a.__isset, b.__isset);
}

CloudCluster::CloudCluster(const CloudCluster& other2) {
  id = other2.id;
  name = other2.name;
  nameForConnect = other2.nameForConnect;
  hazelcastVersion = other2.hazelcastVersion;
  isTlsEnabled = other2.isTlsEnabled;
  state = other2.state;
  token = other2.token;
  certificatePath = other2.certificatePath;
  tlsPassword = other2.tlsPassword;
  __isset = other2.__isset;
}
CloudCluster& CloudCluster::operator=(const CloudCluster& other3) {
  id = other3.id;
  name = other3.name;
  nameForConnect = other3.nameForConnect;
  hazelcastVersion = other3.hazelcastVersion;
  isTlsEnabled = other3.isTlsEnabled;
  state = other3.state;
  token = other3.token;
  certificatePath = other3.certificatePath;
  tlsPassword = other3.tlsPassword;
  __isset = other3.__isset;
  return *this;
}
void CloudCluster::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CloudCluster(";
  out << "id=" << to_string(id);
  out << ", " << "name=" << to_string(name);
  out << ", " << "nameForConnect=" << to_string(nameForConnect);
  out << ", " << "hazelcastVersion=" << to_string(hazelcastVersion);
  out << ", " << "isTlsEnabled=" << to_string(isTlsEnabled);
  out << ", " << "state=" << to_string(state);
  out << ", " << "token=" << to_string(token);
  out << ", " << "certificatePath=" << to_string(certificatePath);
  out << ", " << "tlsPassword=" << to_string(tlsPassword);
  out << ")";
}


Member::~Member() noexcept {
}


void Member::__set_uuid(const std::string& val) {
  this->uuid = val;
}

void Member::__set_host(const std::string& val) {
  this->host = val;
}

void Member::__set_port(const int32_t val) {
  this->port = val;
}
std::ostream& operator<<(std::ostream& out, const Member& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Member::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->uuid);
          this->__isset.uuid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->host);
          this->__isset.host = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Member::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Member");

  xfer += oprot->writeFieldBegin("uuid", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->uuid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("host", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->host);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Member &a, Member &b) {
  using ::std::swap;
  swap(a.uuid, b.uuid);
  swap(a.host, b.host);
  swap(a.port, b.port);
  swap(a.__isset, b.__isset);
}

Member::Member(const Member& other4) {
  uuid = other4.uuid;
  host = other4.host;
  port = other4.port;
  __isset = other4.__isset;
}
Member& Member::operator=(const Member& other5) {
  uuid = other5.uuid;
  host = other5.host;
  port = other5.port;
  __isset = other5.__isset;
  return *this;
}
void Member::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Member(";
  out << "uuid=" << to_string(uuid);
  out << ", " << "host=" << to_string(host);
  out << ", " << "port=" << to_string(port);
  out << ")";
}


Response::~Response() noexcept {
}


void Response::__set_success(const bool val) {
  this->success = val;
}

void Response::__set_message(const std::string& val) {
  this->message = val;
}

void Response::__set_result(const std::string& val) {
  this->result = val;
}
std::ostream& operator<<(std::ostream& out, const Response& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Response::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->success);
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->message);
          this->__isset.message = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->result);
          this->__isset.result = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Response::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Response");

  xfer += oprot->writeFieldBegin("success", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->success);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("message", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->message);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("result", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeBinary(this->result);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Response &a, Response &b) {
  using ::std::swap;
  swap(a.success, b.success);
  swap(a.message, b.message);
  swap(a.result, b.result);
  swap(a.__isset, b.__isset);
}

Response::Response(const Response& other6) {
  success = other6.success;
  message = other6.message;
  result = other6.result;
  __isset = other6.__isset;
}
Response& Response::operator=(const Response& other7) {
  success = other7.success;
  message = other7.message;
  result = other7.result;
  __isset = other7.__isset;
  return *this;
}
void Response::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Response(";
  out << "success=" << to_string(success);
  out << ", " << "message=" << to_string(message);
  out << ", " << "result=" << to_string(result);
  out << ")";
}


ServerException::~ServerException() noexcept {
}


void ServerException::__set_message(const std::string& val) {
  this->message = val;
}
std::ostream& operator<<(std::ostream& out, const ServerException& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ServerException::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->message);
          this->__isset.message = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ServerException::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ServerException");

  xfer += oprot->writeFieldBegin("message", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->message);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ServerException &a, ServerException &b) {
  using ::std::swap;
  swap(a.message, b.message);
  swap(a.__isset, b.__isset);
}

ServerException::ServerException(const ServerException& other8) : TException() {
  message = other8.message;
  __isset = other8.__isset;
}
ServerException& ServerException::operator=(const ServerException& other9) {
  message = other9.message;
  __isset = other9.__isset;
  return *this;
}
void ServerException::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ServerException(";
  out << "message=" << to_string(message);
  out << ")";
}

const char* ServerException::what() const noexcept {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: ServerException";
  }
}

}}}} // namespace
