name: Setup Maven
inputs:
  hazelcast-version:
    description: Hazelcast version to use as a cache key
    required: true
runs:
  using: "composite"
  steps:
    - name: Set ROOT_FOLDER
      shell: bash
      id: get-root-folder
      run: |
        # Path to the root of the checked-out `hazelcast-mono` repo
        # Support execution from non-root directory (e.g. when cloned in a custom subdirectory)
        echo "ROOT_FOLDER=${GITHUB_ACTION_PATH}/../../../" >> ${GITHUB_OUTPUT}
  
    - name: Read Java Config
      shell: bash
      working-directory: ${{ steps.get-root-folder.outputs.ROOT_FOLDER }}
      run: cat .github/java-config.env >> $GITHUB_ENV

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
      
    # https://github.com/madhead/semver-utils/releases/tag/v4.3.0
    - uses: madhead/semver-utils@36d1e0ed361bd7b4b77665de8093092eaeabe6ba
      id: version
      with:
        version: ${{ inputs.hazelcast-version }}
    

      # Based off https://github.com/actions/cache/blob/master/examples.md#java---maven
      # Uses seperate cache action to avoid SNAPSHOTs
    - id: maven-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !**/*SNAPSHOT*/
        # Ideally we run these tests only once per release
        # We need the cache key to be looser to encourage re-use accross multiple patch releases
        key: ${{ runner.os }}-maven-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
