name: Get server matrix

on:
  workflow_call:
    outputs:
      matrix:
        value: ${{ jobs.setup_server_matrix.outputs.matrix }}

jobs:
  setup_server_matrix:
    name: Setup the server test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: get-maintenance-versions
        uses: hazelcast/hazelcast/.github/actions/get-supported-maintenance-versions@master
      - id: calculate-minimum-supported-version
        run: echo "VERSION=$(echo '${{ steps.get-maintenance-versions.outputs.versions }}' | jq '.[0]')" >> ${GITHUB_OUTPUT}
      - name: Checkout to scripts
        uses: actions/checkout@v6
      - name: Set server matrix
        id: set-matrix
        run: |
          echo "matrix=$(
            python \
            get_server_matrix.py \
              --minimum-version ${{ steps.calculate-minimum-supported-version.outputs.VERSION }} \
          )" >> ${GITHUB_OUTPUT}
