name: Test Server Backwards Compatibility

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: Name of the organization to build JARs from. If you want to run the tests with the JARs from your fork, set this to your username.
        required: true
        default: hazelcast
      branch_name:
        description: Name of the branch to build JARs from
        required: true
        default: master
      hz_version:
        description: Version of the JARs that will be built, without the SNAPSHOT suffix.
        required: true
        default: "5.0"
      run_python:
        description: Whether or not to run Python client tests. Set to something else to not run the tests.
        required: true
        default: run
      run_nodejs:
        description: Whether or not to run Node.js client tests (not supported client). Set to "run" to run the tests.
        required: true
        default: dontrun
      run_cpp:
        description: Whether or not to run CPP client tests (not supported client). Set to "run" to run the tests. 
        required: true
        default: dontrun
      run_csharp:
        description: Whether or not to run Csharp client tests. Set to something else to not run the tests. 
        required: true
        default: run
      run_go:
        description: Whether or not to run Go client tests (not supported client). Set to "run" to run the tests. 
        required: true
        default: dontrun
jobs:
  setup_csharp_client_matrix:
    name: Setup the Csharp client test matrix
    if: ${{ github.event.inputs.run_csharp == 'run' }}
    runs-on: windows-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Checkout to scripts
        uses: actions/checkout@v4
      - name: Set client matrix
        id: set-matrix
        run: echo "::set-output name=matrix::$( python get_client_matrix.py --client cs --option tag --use-latest-patch-versions )"
  test_csharp_clients:
    needs: [ setup_csharp_client_matrix ]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        client_tag: ${{ fromJson(needs.setup_csharp_client_matrix.outputs.matrix) }}
        server_kind: [ os, enterprise ]
    name: Test Csharp client ${{ matrix.client_tag }} with ${{ matrix.server_kind }} server
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-enterprise-license
        id: get-enterprise-license
        with:
          hazelcast-version: ${{ github.event.inputs.hz_version }}
      - name: Set up enterprise license key
        shell: pwsh
        run: |
          "HAZELCAST_ENTERPRISE_KEY=${{ secrets[steps.get-enterprise-license.outputs.HAZELCAST_ENTERPRISE_KEY_SECRET] }}" >> $env:GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Read Java Config
        shell: bash
        run: cat ${{ github.workspace }}/.github/java-config.env >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
